version: '3.8'

services:
  trading-bot:
    build: .
    container_name: stock-breakout-bot
    restart: unless-stopped
    env_file:
      - ./env/.env.prod
    ports:
      - "10000:10000"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  logs:
    driver: local